### ISSUE TITLE
Unexcepted token 'Export'

### ISSUE THREAD

**Issue by EdwinCuba** [saostad/fast-node-logger#14]
/home/.../.../.../mssql-change-tracking/dist/index.js:1
export * from "./services/general/index";
^^^^^^

SyntaxError: Unexpected token 'export'

**Comment by saostad** [comment]
I am using typescript for all of my projects. it understand esm module system, probably that's why I never had these problem.

**Comment by EdwinCuba** [comment]
sorry I put the issue in the wrong place, this is a error from  https://github.com/saostad/mssql-change-tracking
